development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:39672634282905d0aa7d627cd61b527d@scat.redistogo.com:10455
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: Calendar_2_production
